name: ndef_example
description: Example for ndef Dart library
version: 0.0.1
homepage: https://github.com/nfcim/ndef
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ndef:
    path: ../
