name: ndef
description: A Dart library to decode & encode NDEF records, supporting multiple types.
version: 0.4.0
homepage: https://github.com/nfcim/ndef

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  uuid: ^4.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.3
