name: ndef
description: A Dart library to decode & encode NDEF records, supporting multiple types.
version: 0.2.4
homepage: https://github.com/nfcim/ndef

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
